//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionDb
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/VimpelCom.MNP.RegionService")]
    public partial class Result : object
    {
        
        private int CodeField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeSet", Namespace="http://schemas.datacontract.org/2004/07/VimpelCom.MNP.RegionService")]
    public partial class ChangeSet : object
    {
        
        private System.DateTime DateAddField;
        
        private long IDField;
        
        private System.DateTime InputChangeDateField;
        
        private bool IsReturnNumberField;
        
        private bool IsUsedField;
        
        private string NumberField;
        
        private string RNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdd
        {
            get
            {
                return this.DateAddField;
            }
            set
            {
                this.DateAddField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InputChangeDate
        {
            get
            {
                return this.InputChangeDateField;
            }
            set
            {
                this.InputChangeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReturnNumber
        {
            get
            {
                return this.IsReturnNumberField;
            }
            set
            {
                this.IsReturnNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUsed
        {
            get
            {
                return this.IsUsedField;
            }
            set
            {
                this.IsUsedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RN
        {
            get
            {
                return this.RNField;
            }
            set
            {
                this.RNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigrationInfo", Namespace="http://schemas.datacontract.org/2004/07/VimpelCom.MNP.RegionService")]
    public partial class MigrationInfo : object
    {
        
        private System.DateTime DateChangeField;
        
        private System.DateTime InputChangeDateField;
        
        private bool IsActiveField;
        
        private RegionDb.NumberRN numberRNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateChange
        {
            get
            {
                return this.DateChangeField;
            }
            set
            {
                this.DateChangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InputChangeDate
        {
            get
            {
                return this.InputChangeDateField;
            }
            set
            {
                this.InputChangeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RegionDb.NumberRN numberRN
        {
            get
            {
                return this.numberRNField;
            }
            set
            {
                this.numberRNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberRN", Namespace="http://schemas.datacontract.org/2004/07/VimpelCom.MNP.RegionService")]
    public partial class NumberRN : object
    {
        
        private string PhoneNumberField;
        
        private string RNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RN
        {
            get
            {
                return this.RNField;
            }
            set
            {
                this.RNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberInfo", Namespace="http://schemas.datacontract.org/2004/07/VimpelCom.MNP.RegionService")]
    public partial class NumberInfo : object
    {
        
        private string HLRField;
        
        private bool IsBeelineSubscriberField;
        
        private string PhoneNumberField;
        
        private string RNField;
        
        private System.Nullable<int> RegionIDField;
        
        private RegionDb.Attribute[] attributesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HLR
        {
            get
            {
                return this.HLRField;
            }
            set
            {
                this.HLRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBeelineSubscriber
        {
            get
            {
                return this.IsBeelineSubscriberField;
            }
            set
            {
                this.IsBeelineSubscriberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RN
        {
            get
            {
                return this.RNField;
            }
            set
            {
                this.RNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegionID
        {
            get
            {
                return this.RegionIDField;
            }
            set
            {
                this.RegionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RegionDb.Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attribute", Namespace="http://schemas.datacontract.org/2004/07/VimpelCom.MNP.RegionService")]
    public partial class Attribute : object
    {
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorInfo", Namespace="http://schemas.datacontract.org/2004/07/VimpelCom.MNP.RegionService")]
    public partial class OperatorInfo : object
    {
        
        private string FederalOperatorCodeField;
        
        private string FederalOperatorNameField;
        
        private string FederalRegionCodeField;
        
        private string FederalRegionNameField;
        
        private string OperatorNameField;
        
        private long PhoneNumberField;
        
        private string RegionNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FederalOperatorCode
        {
            get
            {
                return this.FederalOperatorCodeField;
            }
            set
            {
                this.FederalOperatorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FederalOperatorName
        {
            get
            {
                return this.FederalOperatorNameField;
            }
            set
            {
                this.FederalOperatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FederalRegionCode
        {
            get
            {
                return this.FederalRegionCodeField;
            }
            set
            {
                this.FederalRegionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FederalRegionName
        {
            get
            {
                return this.FederalRegionNameField;
            }
            set
            {
                this.FederalRegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorName
        {
            get
            {
                return this.OperatorNameField;
            }
            set
            {
                this.OperatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegionDb.IRegionContract")]
    public interface IRegionContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionContract/CheckNumberInOperatorPools", ReplyAction="http://tempuri.org/IRegionContract/CheckNumberInOperatorPoolsResponse")]
        System.Threading.Tasks.Task<RegionDb.Result> CheckNumberInOperatorPoolsAsync(string PhoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionContract/GetChangeFromDate", ReplyAction="http://tempuri.org/IRegionContract/GetChangeFromDateResponse")]
        System.Threading.Tasks.Task<RegionDb.ChangeSet[]> GetChangeFromDateAsync(string SystemName, System.Nullable<System.DateTime> CheckDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionContract/GetChangeFromDateFull", ReplyAction="http://tempuri.org/IRegionContract/GetChangeFromDateFullResponse")]
        System.Threading.Tasks.Task<RegionDb.ChangeSet[]> GetChangeFromDateFullAsync(string SystemName, System.Nullable<System.DateTime> CheckDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionContract/GetNumbersFrom", ReplyAction="http://tempuri.org/IRegionContract/GetNumbersFromResponse")]
        System.Threading.Tasks.Task<RegionDb.MigrationInfo[]> GetNumbersFromAsync(string PhoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionContract/GetAttributeValuesByNumbers", ReplyAction="http://tempuri.org/IRegionContract/GetAttributeValuesByNumbersResponse")]
        System.Threading.Tasks.Task<RegionDb.NumberInfo[]> GetAttributeValuesByNumbersAsync(string[] Numbers, string[] AttributeNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionContract/GetAttributeValueByNumber", ReplyAction="http://tempuri.org/IRegionContract/GetAttributeValueByNumberResponse")]
        System.Threading.Tasks.Task<RegionDb.NumberInfo> GetAttributeValueByNumberAsync(string PhoneNumber, string AttributeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionContract/GetUserOperatorInfo", ReplyAction="http://tempuri.org/IRegionContract/GetUserOperatorInfoResponse")]
        System.Threading.Tasks.Task<RegionDb.OperatorInfo> GetUserOperatorInfoAsync(long PhoneNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IRegionContractChannel : RegionDb.IRegionContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class RegionContractClient : System.ServiceModel.ClientBase<RegionDb.IRegionContract>, RegionDb.IRegionContract
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RegionContractClient() : 
                base(RegionContractClient.GetDefaultBinding(), RegionContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRegionContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegionContractClient(EndpointConfiguration endpointConfiguration) : 
                base(RegionContractClient.GetBindingForEndpoint(endpointConfiguration), RegionContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegionContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RegionContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegionContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RegionContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegionContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RegionDb.Result> CheckNumberInOperatorPoolsAsync(string PhoneNumber)
        {
            return base.Channel.CheckNumberInOperatorPoolsAsync(PhoneNumber);
        }
        
        public System.Threading.Tasks.Task<RegionDb.ChangeSet[]> GetChangeFromDateAsync(string SystemName, System.Nullable<System.DateTime> CheckDate)
        {
            return base.Channel.GetChangeFromDateAsync(SystemName, CheckDate);
        }
        
        public System.Threading.Tasks.Task<RegionDb.ChangeSet[]> GetChangeFromDateFullAsync(string SystemName, System.Nullable<System.DateTime> CheckDate)
        {
            return base.Channel.GetChangeFromDateFullAsync(SystemName, CheckDate);
        }
        
        public System.Threading.Tasks.Task<RegionDb.MigrationInfo[]> GetNumbersFromAsync(string PhoneNumber)
        {
            return base.Channel.GetNumbersFromAsync(PhoneNumber);
        }
        
        public System.Threading.Tasks.Task<RegionDb.NumberInfo[]> GetAttributeValuesByNumbersAsync(string[] Numbers, string[] AttributeNames)
        {
            return base.Channel.GetAttributeValuesByNumbersAsync(Numbers, AttributeNames);
        }
        
        public System.Threading.Tasks.Task<RegionDb.NumberInfo> GetAttributeValueByNumberAsync(string PhoneNumber, string AttributeName)
        {
            return base.Channel.GetAttributeValueByNumberAsync(PhoneNumber, AttributeName);
        }
        
        public System.Threading.Tasks.Task<RegionDb.OperatorInfo> GetUserOperatorInfoAsync(long PhoneNumber)
        {
            return base.Channel.GetUserOperatorInfoAsync(PhoneNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRegionContract))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRegionContract))
            {
                return new System.ServiceModel.EndpointAddress("http://ms-rplweb001:10001/Region.svc");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RegionContractClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRegionContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RegionContractClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRegionContract);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRegionContract,
        }
    }
}
